from enum import Enum

class JSONType(Enum):
    STRING= 'STRING'
    NUMBER= 'NUMBER'
    BOOLEAN= 'BOOLEAN'
    NULL= 'NULL'
    OBJECT= 'OBJECT'
    ARRAY= 'ARRAY'
    OPEN_BRACE= 'OPEN_BRACE'
    CLOSE_BRACE= 'CLOSE_BRACE'
    OPEN_BRACKET= 'OPEN_BRACKET'
    CLOSE_BRACKET= 'CLOSE_BRACKET'
    COLON= 'COLON'
    COMMA= 'COMMA'